package yj.song.notiaggregate.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import yj.song.notiaggregate.db.NotificationAppEntity;

import yj.song.notiaggregate.db.NotificationAppEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig notificationAppEntityDaoConfig;

    private final NotificationAppEntityDao notificationAppEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        notificationAppEntityDaoConfig = daoConfigMap.get(NotificationAppEntityDao.class).clone();
        notificationAppEntityDaoConfig.initIdentityScope(type);

        notificationAppEntityDao = new NotificationAppEntityDao(notificationAppEntityDaoConfig, this);

        registerDao(NotificationAppEntity.class, notificationAppEntityDao);
    }
    
    public void clear() {
        notificationAppEntityDaoConfig.clearIdentityScope();
    }

    public NotificationAppEntityDao getNotificationAppEntityDao() {
        return notificationAppEntityDao;
    }

}
